src/app.js
src/events.js

- App.currentElement
- App.currentEvent
- Automatic `preventDefault` onclick

Custom event handling

---

README.md
src/controller.js

add methods: url and getParam

---

README.md
package-lock.json
package.json
src/app.js
src/controller.js

- avoid depending directly on @rails/ujs 👌 (this make it easy to work with different `ujs` versions and non-Rails apps)
- add toggleClass method (supersedes #6)

do not depend directly on rails-ujs, inject it from client app

---

README.md
index.js
src/app.js
src/core.js
src/router.js
src/utils.js

remove the RalixCtrl concept 

---

README.md
src/core.js

add url support for setParam

---

README.md
src/core.js

Add Reload as a core function

---

README.md

Closes https://github.com/ralixjs/ralix/issues/16

Update README with new Logo

---

README.md
src/core.js

get and set attributes

---

README.md
src/core.js

Add Core method to serialize form params

---

README.md
src/core.js

Data attributes stuff:
- data("#menu") => returns dataset
- data("#menu", "status") => returns data-status value
- data("#menu", "status", "closed") => sets data-status="closed"

Data attributes

---

README.md
src/core.js

new method to add event listeners: on

---

README.md
src/app.js
src/core.js
src/templates.js

Closes #33 
Just a proof of concept for now. Example here: https://github.com/ralixjs/ralix-todomvc/pull/3
Basically, Ralix templates are js functions with Template literals.
Example
```js
// app/javascript/templates/index.js
export const todoItem = ({ id, label }) => `
<div id="item_${id}">
<input type="checkbox" onclick="toggleCheck(${id})">
<label>${label}</label>
<button onclick="destroyItem(${id})"></button>
</div>
`
// call it via
render('todoItem', { id: id, value: value })
```

Templates [POC]

---

docs/CORE_API.md
src/core.js

Classes helpers with multiple selectors

---

src/core.js

CodeClimate is reporting too much duplication after merging #38:

Refactor class methods to avoid duplication (reported by CodeClimate)

---

README.md
docs/CORE_API.md
src/core.js

Add ajax helpers

---

README.md
src/core.js

The idea is to be able to associate events or apply methods for multiple DOM objects through string like `.class` or `input[type]=checkbox`.
Until now it only get the first object it finds using [`find()`](https://github.com/ralixjs/ralix/blob/master/src/core.js#L184). Using any class for example will only be applied on the first element it gets.
**NOTE**
It is on WIP and for discussion because we have to speak what methods will be changed firstly

Reference classes or attributes to select DOM objects

---

src/core.js

move private functions _element and _elements implementation to find and findAll

---

README.md
docs/HELPERS_API.md
docs/PHILOSOPHY.md
src/app.js
src/helpers.js

The new configuration just needs to require `turbo-rails`
```js
// Dependencies
import Rails         from '@rails/ujs'
import { RalixApp }  from 'ralix'
require("@hotwired/turbo-rails")
const App = new RalixApp({
rails_ujs: Rails,
routes: {}, // Your routes here
components: [] // Your components here
})
Rails.start()
App.start()
```

Turbo support

---

README.md
docs/HELPERS_API.md
src/helpers.js

Closes https://github.com/ralixjs/ralix/issues/59

Remove show & hide

---

src/events.js
src/helpers.js
tests/helpers.test.js

Changes to set `currentElement` and `currentEvent` in the `on` helper method

Set currentElement & currentEvent in on()

---

CHANGELOG.md

🎉 Time to mark v1.0 🎉
https://github.com/ralixjs/ralix/compare/v0.10.0...master

Prepare v1 release 🎉

---

docs/HELPERS_API.md
src/helpers.js
tests/helpers.test.js

**DESCRIPTION**
findParent(el) -> el.parentElement
findParent(el, query) -> first matched parent
findParents(el, query) -> array of matches

Add findParent and findParents helpers

---

src/helpers.js

[FIX] Automatic preventDefault conditions [hacktoberfest-accepted]

---

README.md
src/helpers.js

Also:
- move private functions near related block
- separate blocks with a comment with the title
- minor README updates

Re-order helpers to match docs and tests

---

CHANGELOG.md
README.md
docs/DESIGN.md
docs/HELPERS_API.md
src/helpers.js
tests/helpers.test.js
yarn.lock

The helper `setUrl` is a bit "obscure" 😅... why you would need to change the host without a redirect 🤔? It seems something too "low level" for Ralix. It was more a private function that we decided, at that time, to expose it as public api. After writing more than 10 Ralix apps we've never use it, so I think it's time to ✂️
I take the opportunity to refactor a bit the `setParams` helper and how it works:
- simpler signature: 
`setParam(param, value, { url = currentUrl(), update = false } = {})` => 
`setParam(param, value)`
- always update history via pushState
- if `value` is `null`, remove the param from current url object
- allow to set multiple values at once
**EXTRAS**
- ➕ Implements and closes #76 
- 📝 minor documentation enhancements
- ⬆️ `yarn upgrade`

🔧 Refactor getParams/setParams and ✂️ remove setUrl

---

docs/HELPERS_API.md
src/helpers.js
tests/helpers.test.js

- New optional parameter `classValue`, if given the class will be added or removed accordingly
Closes #78

`toggleClass` accepts a boolean to force add/remove given class

---

docs/HELPERS_API.md

- new `on` option added in the docs (ref #90)

[DOCS] options in on helper added to helpers documentation

---

docs/HELPERS_API.md
src/helpers.js
tests/helpers.test.js
tests/templates.test.js
yarn.lock

**WHY?**
Combo of `render` + `insertHTML` for convenience (without the need to pass `sanitize: false`), as the templates are already sanitized.

Add new helper `insertTemplate` 💫

---

src/templates.js

This pull request updates the way string sanitization is handled in the `Templates` class by replacing the direct usage of `DOMPurify` with our custom sanitization method. This change centralizes and potentially enhances sanitization logic.

[Fix] Use same sanitize config
